# Generated by Django 5.2.17 on 2026-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_activated_at_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
