# Generated by Django 5.2.17 on 2026-09-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_options_user_unique_user_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user_constraint',
        ),
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
