# Generated by Django 5.2.17 on 2026-09-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_unique_user_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvitation',
            name='token_hash',
            field=models.CharField(max_length=64),
        ),
    ]
