# Generated by Django 5.2.17 on 2026-09-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userinvitation_token_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
