# Generated by Django 5.2.17 on 2026-09-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome do cliente')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email para contato')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='Telefone para contato')),
                ('address', models.CharField(blank=True, verbose_name='Endereço')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('email__gt', ''), ('phone__gt', ''), _connector='OR'), name='client_has_contact')],
            },
        ),
    ]
