# Generated by Django 5.2.17 on 2026-09-23 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_options_client_unique_client_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=7, verbose_name='Placa do veiculo')),
                ('brand', models.CharField(max_length=60, verbose_name='Marca do veiculo')),
                ('model', models.CharField(max_length=60, verbose_name='Modelo do veiculo')),
                ('year', models.CharField(max_length=4, verbose_name='Ano do veiculo')),
                ('color', models.CharField(max_length=30, verbose_name='Cor do veiculo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Veiculo ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='client.client')),
            ],
            options={
                'verbose_name': 'Veiculo',
                'verbose_name_plural': 'Veiculos',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('plate',), name='unique_car_constraint')],
            },
        ),
    ]
