# Generated by Django 5.2.17 on 2026-09-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_vehicle'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='unique_car_constraint',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='is_active',
            new_name='active',
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('plate',), name='unique_car_constraint'),
        ),
    ]
