# Generated by Django 5.2.17 on 2026-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_vehicle_unique_car_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='unique_car_constraint',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('plate',), name='unique_car_constraint'),
        ),
    ]
